[workspace.package]
version = "0.1.0"
description = "Raft consensus algorithm in Rust"
authors = ["June Yi"]
license = "MIT"
edition = "2024"

[workspace]
members = [
    "crates/cli", 
    "crates/kvdb", 
    "crates/net", 
    "crates/raft",
]
resolver = "2"
